### ISSUE TITLE
Le comarquage v3.3 ne fonctionne plus

### ISSUE THREAD

**Issue by nd-** [ipeos-and-co/spip_comarquagev3#17]
https://lecomarquage.service-public.fr/ répond en 403 Forbidden

Il semblerait que le service en v3.3 ait été coupé récemment : 
https://github.com/ipeos-and-co/spip_comarquagev3.git

Sur un site qui l'utilise, les pages avec le modèle moulinent dans le vide au lieu d'afficher une erreur (ou rien), et les processus PHP au niveau du serveur finissent par être tous en état instable, et c'est tout le site qui se met à répondre en 503.

Je désactive le plugin pour l'instant.

Une mise à jour vers le service en V4 (données locales) est elle prévue ?

**Comment by Cerdic** [comment]
corrigé par #15
