### ISSUE TITLE
Problème d'enchainement de tags et leur affichage.

### ISSUE THREAD

**Issue by Ybbet** [ipeos-and-co/spip_comarquagev3#2]
Hello,

Il semble qu'il persiste un "bug" sur cette version du plugin. Il s'agit de l'affichage consécutif de tags. **Exemple :** 
_Dans le flux xml  :_
- tag paragraphe
- tag liste
- tag paragraphe
- tag paragraphe
- tag paragraphe

_A l'affichage sur le site :_ 
- tag paragraphe 
- tag paragraphe
- tag paragraphe
- tag paragraphe
- tag liste

Pour reproduire le bug : https://www.service-public.fr/associations/vosdroits/F1122
`<comarquage|categorie=associations|xml=F1122>`
cf. Type de dissolution > Dissolution administrative

**Comment by Ybbet** [comment]
J'ai continué à chercher d'où viendrait le soucis. Sur cette version, c'est la fonction `inc_comarquagexml_to_array` qui transforme le xml en array. Le problème est qu'il regroupe par tag au lieu de les mettre dans l'ordre où le tag est rencontré.

Est-ce que c'est la ligne suivante qui pose soucis ? https://github.com/ipeos-and-co/spip_comarquagev3/blob/master/comarquage_fonctions.php#L226

**Comment by psychoz971** [comment]
Oui en effet j'ai vu l'erreur. En fait c'est le parsing avec SimpleXML qui pose problème. Le tableau groupe les balises ensemble. Pratique pour certains cas, mais dans d'autre ça brise la structure.

Il faut modifier la fonction `fluxXmlObjToArr` en ajoutant les bons noms de balises à la ligne https://github.com/ipeos-and-co/spip_comarquagev3/blob/master/comarquage_fonctions.php#L312 pour que l'enchainement des blocs soit respecté pour ces balises.

**Comment by psychoz971** [comment]
Je viens de mettre à jour pour que la structure ne soit plus groupée pour `paragraphe`, `cas`, `chapitre`, `texte` et `souschapitre`.

Si une autre balise demande à avoir une structure ordonnée au lieu de groupée il suffira de l'ajouter au tableau `orderedTags` https://github.com/ipeos-and-co/spip_comarquagev3/blob/master/comarquage_fonctions.php#L270 et de modifier dans `xml_templates/balises/` le squelette correspondant.
