### ISSUE TITLE
Balise Paragraphe et son interprétation DOM

### ISSUE THREAD

**Issue by Ybbet** [ipeos-and-co/spip_comarquagev3#5]
Bonjour,

Il semble qu'il y a un soucis dans le parser pour le tag paragraphe. En effet, lorsque la balise _"\<paragraphe>"_ contient des balises, le contenu textuel de _\<paragraphe>_ est purgé du texte de ses sous balises.

cf. https://lecomarquage.service-public.fr/vdd/3.0/part/xml/F33955.xml

`<Paragraphe>la FTTB (<Citation>fiber to the building</Citation> qui signifie <Citation> fibre jusqu'à l'immeuble</Citation>) : c'est également une connexion qui utilise en partie le réseau en cuivre. Dans ce cas, la partie en fibre s'arrête au pied des immeubles. </Paragraphe>`

Sera reproduit de la façon suivante :
`la FTTB ( qui signifie ) : c'est également une connexion qui utilise en partie le réseau en cuivre. Dans ce cas, la partie en fibre s'arrête au pied des immeubles.
fiber to the building
fibre jusqu'à l'immeuble`

Au lieu de :
`la FTTB (fiber to the building qui signifie  fibre jusqu'à l'immeuble) : c'est également une connexion qui utilise en partie le réseau en cuivre. Dans ce cas, la partie en fibre s'arrête au pied des immeubles.`

**Comment by psychoz971** [comment]
Bonjour,

J'ai fait un test sur cette page et le comportement je n'ai pas vu le comportement que tu indiques.

Modifier `<blockquote>` pour les citations par `<span><em>` est une très bonne idée car ça évite de casser la structure de la page, mais sinon la récursivité des balises à l'intérieur de paragraphe a l'air de se faire correctement. Justement nous avions ce problème en v1.0.1 mais ça a été corrigé dès la v1.0.2.

Je ferme donc cet issue et publie le merge sur la zone. Merci
